name: Greate Expectations Reports for The Lakehouse

on:
  push:
    branches:
    - master
  schedule:
    - cron: "* */3 * * *"

env:
  LANG: "zh_CN.UTF-8"

jobs:
  get_report_html:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
        architecture: 'x64'

    - name: Install databricks-cli
      uses: microsoft/install-databricks-cli@v1.0.0

    - name: Get lily strong rule report files from DBFS
      continue-on-error: true
      run: |
        databricks fs cp -r "${{secrets.GE_LILY_DATADOCS_ROOT}}"/local_site ./lily
      env:
        DATABRICKS_HOST: "${{secrets.DATABRICKS_HOST}}"
        DATABRICKS_USERNAME: "${{secrets.DATABRICKS_USERNAME}}"
        DATABRICKS_TOKEN: "${{secrets.DATABRICKS_TOKEN}}"

    - name: Get lily weak rule report files from DBFS
      continue-on-error: true
      run: |
        databricks fs cp -r "${{secrets.GE_LILY_WEAK_DATADOCS_ROOT}}"/local_site ./lily_weak
      env:
        DATABRICKS_HOST: "${{secrets.DATABRICKS_HOST}}"
        DATABRICKS_USERNAME: "${{secrets.DATABRICKS_USERNAME}}"
        DATABRICKS_TOKEN: "${{secrets.DATABRICKS_TOKEN}}"

    - name: Get extended lily(middle tables) report files from DBFS
      continue-on-error: true
      run: |
        databricks fs cp -r "${{secrets.GE_LILYX_DATADOCS_ROOT}}"/local_site ./lilyx
      env:
        DATABRICKS_HOST: "${{secrets.DATABRICKS_HOST}}"
        DATABRICKS_USERNAME: "${{secrets.DATABRICKS_USERNAME}}"
        DATABRICKS_TOKEN: "${{secrets.DATABRICKS_TOKEN}}"

    - name: Get observable report files from DBFS
      continue-on-error: true
      run: |
        databricks fs cp -r "${{secrets.GE_OBSERVABLE_DATADOCS_ROOT}}"/local_site ./observable
      env:
        DATABRICKS_HOST: "${{secrets.DATABRICKS_HOST}}"
        DATABRICKS_USERNAME: "${{secrets.DATABRICKS_USERNAME}}"
        DATABRICKS_TOKEN: "${{secrets.DATABRICKS_TOKEN}}"

    - name: Get fvm(mainnet) report files from DBFS
      continue-on-error: true
      run: |
        databricks fs cp -r "${{secrets.GE_FVMSTAT_MAINNET_DATADOCS_ROOT}}"/local_site ./fvmstat_mainnet
      env:
        DATABRICKS_HOST: "${{secrets.DATABRICKS_HOST}}"
        DATABRICKS_USERNAME: "${{secrets.DATABRICKS_USERNAME}}"
        DATABRICKS_TOKEN: "${{secrets.DATABRICKS_TOKEN}}"

    - name: Deploy pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        force_orphan: true

